[package]
name = "capstone-sys"
version = "0.1.0"
authors = ["Mickaël Delahaye <mickael.delahaye@gmail.com>"]
build = "build.rs"

[dependencies]
libc=">=0.2"

[build-dependencies]
gcc="0.3"
pkg-config = "0.3"
